server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona requisições de API para os microsserviços
    location /api/produtos {
        proxy_pass http://estoque-api:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/analise {
        proxy_pass http://estoque-api:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/categorias {
        proxy_pass http://estoque-api:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/notasfiscais {
        proxy_pass http://faturamento-api:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback — sempre retorna index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
